repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.1
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.375
    hooks:
      - id: pyright
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.6.2
    hooks:
      # Compile requirements
      - id: uv-lock
      - id: uv-export
        args: ["--frozen", "--no-dev", "--output-file=requirements.txt"]
      - id: uv-export
        args: ["--frozen", "--all-groups", "--output-file=requirements.dev.txt"]
  - repo: local
    hooks:
      - id: pip-audit
        name: pip-audit
        entry:
          uv run pip-audit --ignore-vuln CVE-2025-69872 --ignore-vuln
          CVE-2026-1703 --ignore-vuln GHSA-537c-gmf6-5ccf
        language: system
        pass_filenames: false
        always_run: true
